package org.drools.workshop;

import org.drools.workshop.model.Person;
import org.drools.workshop.model.Person.Employment;
import java.util.List;
import org.drools.workshop.service.*;

global ReportService reportService;

declare IdentityIsValid
    person: Person @key
end

rule "Person with cell phone"
    when
        $p: IdentityIsValid($p.person.phoneNumber != null, $p.person.phoneNumber.startsWith("13"))
    then
        reportService.notify($p.getPerson().getName() + " ==> 用户符合准入要求");
end
